# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Life_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Life_comment_created_date', models.DateField(default=django.utils.timezone.now)),
                ('Life_comment_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Life_comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(default='業障研發工程師', max_length=200)),
                ('Content', models.TextField()),
                ('Life_comment_reply_created_date', models.DateField(default=django.utils.timezone.now)),
                ('Life_comment_reply_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='life.Life_comment')),
            ],
        ),
        migrations.CreateModel(
            name='Life_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Life_title', models.CharField(max_length=200)),
                ('Life_content', models.TextField(blank=True)),
                ('Life_photo', models.URLField(blank=True)),
                ('Life_post_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='life_comment',
            name='Life_comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='life.Life_post'),
        ),
    ]
