# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LifeTitle', models.CharField(max_length=200)),
                ('LifeContent', models.TextField(blank=True)),
                ('LifePhoto', models.URLField(blank=True)),
                ('LifeCreated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
