# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Dish_comment_created_date', models.DateField(default=django.utils.timezone.now)),
                ('Dish_comment_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dish_comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(default='業障研發工程師', max_length=200)),
                ('Content', models.TextField()),
                ('Dish_comment_reply_created_date', models.DateField(default=django.utils.timezone.now)),
                ('Dish_comment_reply_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dish.Dish_comment')),
            ],
        ),
        migrations.CreateModel(
            name='Dish_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_title', models.CharField(max_length=200)),
                ('Dish_content', models.TextField(blank=True)),
                ('Dish_photo', models.URLField(blank=True)),
                ('Dish_post_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.AddField(
            model_name='dish_comment',
            name='Dish_comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dish.Dish_post'),
        ),
    ]
