# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 07:09
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_post',
            name='Dish_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
